# Generated by Django 2.1.5 on 2019-01-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.CharField(max_length=1000)),
                ('is_enabled', models.BooleanField(default=True)),
                ('price', models.IntegerField()),
                ('viewed', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=2)),
                ('count', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
