# Generated by Django 2.2.1 on 2019-06-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.ImageField(blank=True, null=True, upload_to='brand')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('folder', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('viewed', models.IntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=100)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.AttributeValue')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('file', models.ImageField(upload_to='media')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Item')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
    ]
