# Generated by Django 2.1.7 on 2019-03-09 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_discounts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Discounts',
            new_name='Discount',
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
    ]
