# Generated by Django 2.1.5 on 2019-01-21 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_item_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='category'),
            preserve_default=False,
        ),
    ]
