# Generated by Django 2.1.7 on 2019-03-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_auto_20190309_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='discount',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
