# Generated by Django 2.1.7 on 2019-03-10 10:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20190310_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='dateEnd',
            field=models.DateField(default=datetime.datetime(2019, 3, 10, 10, 49, 51, 723629, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='dateStart',
            field=models.DateField(default=datetime.datetime(2019, 3, 10, 10, 49, 51, 723578, tzinfo=utc)),
        ),
    ]
