# Generated by Django 2.1.7 on 2019-03-10 11:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20190310_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='item',
        ),
        migrations.AddField(
            model_name='discount',
            name='img',
            field=models.ImageField(null=True, upload_to='discounts'),
        ),
        migrations.AddField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='discount',
            name='dateEnd',
            field=models.DateField(default=datetime.datetime(2019, 3, 10, 11, 4, 54, 930455, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='dateStart',
            field=models.DateField(default=datetime.datetime(2019, 3, 10, 11, 4, 54, 930420, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='discountitem',
            name='disc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Discount'),
        ),
        migrations.AddField(
            model_name='discountitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Item'),
        ),
    ]
