# Generated by Django 2.1.5 on 2019-01-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_atribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='atr',
            field=models.ManyToManyField(to='market.Atribute'),
        ),
    ]
