# Generated by Django 2.1.5 on 2019-01-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_items_atr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30)),
                ('attr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Atribute')),
            ],
        ),
        migrations.RemoveField(
            model_name='items',
            name='atr',
        ),
        migrations.AddField(
            model_name='itemattribute',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.Items'),
        ),
    ]
