# Generated by Django 2.1.7 on 2019-03-10 12:08

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20190310_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='dateEnd',
            field=models.DateField(default=datetime.datetime(2019, 3, 10, 12, 8, 9, 796816, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='dateStart',
            field=models.DateField(default=datetime.datetime(2019, 3, 10, 12, 8, 9, 796783, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discountitem',
            name='disc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Discount'),
        ),
    ]
