# Generated by Django 2.1.5 on 2019-01-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20190117_0918'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemattribute',
            unique_together={('attr', 'item')},
        ),
    ]
