# Generated by Django 2.1.7 on 2019-03-11 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20190310_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountitem',
            name='dateEnd',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 11, 9, 54, 15, 605911, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='discountitem',
            name='dateStart',
            field=models.DateField(blank=True, default=datetime.datetime(2019, 3, 11, 9, 54, 15, 605877, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='dateEnd',
            field=models.DateField(default=datetime.datetime(2019, 3, 11, 9, 54, 15, 606386, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='dateStart',
            field=models.DateField(default=datetime.datetime(2019, 3, 11, 9, 54, 15, 606365, tzinfo=utc)),
        ),
    ]
