# Generated by Django 2.1.7 on 2019-03-11 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20190311_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='dateEnd',
            field=models.DateField(default=datetime.datetime(2019, 3, 11, 9, 55, 13, 949505, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='dateStart',
            field=models.DateField(default=datetime.datetime(2019, 3, 11, 9, 55, 13, 949470, tzinfo=utc)),
        ),
    ]
