# Generated by Django 2.1.7 on 2019-03-18 19:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_auto_20190311_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='dateEnd',
            field=models.DateField(default=datetime.datetime(2019, 3, 18, 19, 37, 52, 201499, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='dateStart',
            field=models.DateField(default=datetime.datetime(2019, 3, 18, 19, 37, 52, 201452, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='discount',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='discounts'),
        ),
    ]
