# Generated by Django 2.2.1 on 2019-06-02 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.Item'),
        ),
    ]
